#!/bin/bash
# GDZ instalinux v0.4c #
# SQ2MTG 2024

# Sprawdzanie, czy skrypt jest uruchomiony jako uzytkownik sudo
if [[ $(id -u) -ne 0 ]]; then
    echo "Ten skrypt wymaga uprawnien administratora (sudo)."
    while true; do
        read -p "Czy chcesz podniesc uprawnienia? (y/n): " choice
        case "$choice" in
            y|Y ) su -c "$(readlink -f "$0")"; exit;;
            n|N ) echo "Przerywam skrypt."; exit 1;;
            * ) echo "Uzyj 'y' lub 'n'.";;
        esac
    done
fi

# Sprawdzenie, czy uzytkownik 'gdz' jest juz dodany do sudoers
if grep -q "^gdz " /etc/sudoers; then
    echo "Uzytkownik 'gdz' jest juz dodany do sudoers."
else
    echo -e "\033[0mINSTALINUX: \033[41;1mDodaje nowego uzytkownika do sudoers\033[0m"
    echo 'gdz  ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
    sleep 1
fi


# Sprawdzanie wolnego miejsca na dysku
check_disk_space() {
    echo -e "\033[0mINSTALINUX: \033[41;1mSprawdzam dostepne miejsce na dysku...\033[0m"
    local disk_usage=$(df -h . | awk 'NR==2 {print $5}' | sed 's/%//')
    if [ $disk_usage -gt 85 ]; then
        echo -e "\033[0mINSTALINUX: \033[41;1mWolne miejsce na dysku jest niewystarczajace! <15%.\033[0m"
        while true; do
            read -p "Czy chcesz kontynuowac? (y/n): " choice
            case "$choice" in
                y|Y ) echo "Kontynuuje..."; break;;
                n|N ) echo "Przerywam skrypt."; exit 1;;
                * ) echo "Uzyj 'y' lub 'n'.";;
            esac
        done
    else
        echo "Wolne miejsce na dysku jest wystarczajace zeby kontynuowac..."
        sleep 3
    fi
}

## Najwazniejsze BHP
clear

## Glowny skrypt
echo "██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗";
echo "██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║████╗  ██║██║   ██║╚██╗██╔╝";
echo "██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝ ";
echo "██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║██║╚██╗██║██║   ██║ ██╔██╗ ";
echo "██║██║ ╚████║███████║   ██║   ██║  ██║███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗";
echo "╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝";
echo "                                                                            ";
sleep 2
read -p "Skrypt instalacyjny linux, nacisnij ENTER zeby kontynuowac..."

clear

echo -e "\033[0mINSTALINUX: \033[41;1mPInstalacja dialog i sudo\033[0m"

apt install sudo -y &&
apt install dialog -y &&
clear

echo -e "\033[0mINSTALINUX: \033[41;1mTworze katalogi robocze w /opt\033[0m"
sudo mkdir -p /opt/{log,skrypty,backup,cloud,cfg}
chmod 777 /opt/*
echo -e "\033[0mINSTALINUX: \033[41;1mKatalogi utworzone\033[0m"
sleep 2

check_disk_space

onoff=off
cmd=(dialog --output-fd 1 --separate-output --extra-button --extra-label 'Wszystkie' --cancel-label 'Zadne' --checklist 'Wybierz pakiety do instalacji:' 0 0 0)
load-dialog () {
    options=(
                1 'Update & Upgrade' $onoff
                2 'curl git make cmake gdebi wget gzip tar autoconf ssh' $onoff
                3 'build-essential  software-properties-common g++ gcc' $onoff
                4 'golang  nodejs  npm' $onoff
                5 'php packet' $onoff
                6 'libs packet' $onoff
                7 'ALSA Audio libs' $onoff
                8 'htop  rdate  chkrootkit ' $onoff
                9 'Samba  CIFS + mount cloud' $onoff
    )
    choices=$("${cmd[@]}" "${options[@]}")
}
load-dialog
exit_code="$?"
while [[ $exit_code -ne 0 ]]; do
    case $exit_code in
        1) clear; onoff=off; load-dialog;;
        3) clear; onoff=on; load-dialog;;
    esac
    exit_code="$?"
done
clear
for choice in $choices
do
    case $choice in
        1) sudo apt update -y && sudo apt upgrade -y && check_disk_space ;;
        2) check_disk_space && sudo apt install curl git make cmake wget gzip autoconf tar ssh g++ gcc -y ;;
        3) check_disk_space && sudo apt install build-essential software-properties-common -y ;;
        4) check_disk_space && sudo apt install golang nodejs npm -y ;;
        5) check_disk_space && sudo apt install php libapache2-mod-php php-mbstring php-cgi php-common php-curl -y ;;
        6) check_disk_space && sudo apt install libpopt-dev libsigc++-2.0-dev libgcrypt20-dev libgsm1-dev librtlsdr-dev libusb-dev libjsoncpp-dev libgpiod2 libgpiod-dev libcurl4-openssl-dev libjson-perl libwww-perl -y ;;
        7) check_disk_space && sudo apt install alsa-utils libspeex-dev libspeexdsp-dev libopus-dev libvorbis-dev libasound2-dev -y ;;
        8) check_disk_space && sudo apt install htop rdate chkrootkit -y ;;
        9) check_disk_space && sudo apt install cifs-utils psmisc samba winbind -y ;;
    esac
done

clear
echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja oprogramowania i modulow opcjonalnych\033[0m"
sleep 2

onoff2=off
cmd2=(dialog --output-fd 1 --separate-output --extra-button --extra-label 'Wszystkie' --cancel-label 'Zadne' --checklist 'Wybierz oprogramowanie do skonfigurowania:' 0 0 0)
load-dialog () {
    options=(
                1 'Przywrocenie rc.local' $onoff2
                2 'SDR RTL + BLACKLIST' $onoff2
                3 'SDR RSP1' $onoff2
                4 'VPN ZeroTier' $onoff2
                5 'Cockpit + plugins' $onoff2
                6 'Docker + Compose + portainer' $onoff2
                7 'Zabbix-agent2' $onoff2
                8 'Logs > graylog' $onoff2
				9 'Lynis audit' $onoff2
    )
    choices2=$("${cmd2[@]}" "${options[@]}")
}
load-dialog

exit_code="$?"
while [[ $exit_code -ne 0 ]]; do
    case $exit_code in
        1) clear; onoff2=off; load-dialog;;
        3) clear; onoff2=on; load-dialog;;
    esac
    exit_code="$?"
done
clear
for choice2 in $choices2
do
    case $choice2 in
        1) clear && echo -e "\033[0mINSTALINUX: \033[41;1mAktywuje rc.local...\033[0m" && cd ~ && bash <(curl -s 10.10.0.10/data/rc-local.txt) && echo -e "\033[0mINSTALINUX: \033[41;1mrc.local aktywny\033[0m" ;;
        2) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja RTL-SDR\033[0m" && cd ~ && git clone https://github.com/osmocom/rtl-sdr && cd rtl-sdr/ && mkdir build && cd build && cmake ../ -DINSTALL_UDEV_RULES=ON -DDETACH_KERNEL_DRIVER=ON && make && sudo make install && sudo cp ../rtl-sdr.rules /etc/udev/rules.d/ && sudo ldconfig && echo "blacklist dvb_core blacklist dvb_usb_rtl28xxu
blacklist dvb_usb_rtl2832u
blacklist dvb_usb_v2
blacklist e4000
blacklist fc0013
blacklist r820t
blacklist rtl2830
blacklist rtl2832
blacklist sdr_msi3101
blacklist msi001
blacklist msi2500" > no-rtl.conf && sudo mv no-rtl.conf /etc/modprobe.d/ ;;
        3) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja RSP1 SDR\033[0m" && cd ~ && git clone https://github.com/f4exb/libmirisdr-4.git && cd libmirisdr-4 && mkdir build; cd build && cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/libmirisdr .. && make -j $(nproc) install ;;
        4) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja VPN - ZeroTier\033[0m" && cd ~ && curl -s https://install.zerotier.com | sudo bash && sudo service zerotier-one start && sudo zerotier-cli join $(curl -s http://10.10.0.10/data/zerotier) ;;
        5) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja modulu Cockpit\033[0m" && cd ~ && sudo apt-get install -y cockpit && curl -LO https://github.com/45Drives/cockpit-identities/releases/download/v0.1.12/cockpit-identities_0.1.12-1focal_all.deb && sudo apt install ./cockpit-identities_0.1.12-1focal_all.deb && curl -LO https://github.com/45Drives/cockpit-file-sharing/releases/download/v3.2.9/cockpit-file-sharing_3.2.9-2focal_all.deb && sudo apt install ./cockpit-file-sharing_3.2.9-2focal_all.deb ;;
        6) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mKonfiguracja pakietu Docker\033[0m" && cd ~ && curl -fsSL https://test.docker.com -o test-docker.sh && sudo sh test-docker.sh && apt install docker-compose -y && docker run -d \
  -p 9001:9001 \
  --name portainer_agent \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/lib/docker/volumes:/var/lib/docker/volumes \
  portainer/agent:latest ;;
        7) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mInstalacja zabbix-agent2\033[0m" && cd ~ && wget 10.10.0.10/data/zabbix && chmod +x zabbix && bash ./zabbix ;;
        8) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mInstalacja skryptu Graylog\033[0m" && sudo apt install syslog-ng -y && cd ~ && wget 10.10.0.10/data/graylog.conf && mv graylog.conf /etc/syslog-ng/conf.d/ && syslog-ng-ctl reload;;
		9) check_disk_space && clear && echo -e "\033[0mINSTALINUX: \033[41;1mInstalacja Lynis audit tool\033[0m" && sudo curl -fsSL https://packages.cisofy.com/keys/cisofy-software-public.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/cisofy-software-public.gpg && sudo echo "deb [arch=amd64,arm64 signed-by=/etc/apt/trusted.gpg.d/cisofy-software-public.gpg] https://packages.cisofy.com/community/lynis/deb/ stable main" | sudo tee /etc/apt/sources.list.d/cisofy-lynis.list && sudo apt install apt-transport-https && echo "deb https://packages.cisofy.com/community/lynis/deb/ stable main" | sudo tee /etc/apt/sources.list.d/cisofy-lynis.list && apt update && apt install lynis -y ;;
    esac
done

clear && echo -e "\033[0mINSTALINUX: \033[41;1mUsuwanie plikow roboczych\033[0m" &&
sleep 5 &&

sudo apt clean && sudo apt autoclean &&
cd ~ &&
rm -r cockpit* zabbix* libmirisdr-4/ test-docker.sh &&
clear && echo -e "\033[0mINSTALINUX: \033[41;1mInstalacja zakonczona\033[0m" &&
sleep 3

exit 0
